version: '3.5'

services:

  reverse-proxy:
    container_name: reverse-proxy
    image: reverse-proxy/nginx:alpine
    build:
      context: ./nginx
    restart: always
    links:
      - "web:tomcat"
    depends_on:
      - web
    ports:
      - "80:80"

  web:
    container_name: web
    image: tomcat
    restart: always
    volumes:
      - ~/tomcat/logs:/usr/local/tomcat/logs
      - ~/tomcat/war:/usr/local/tomcat/webapps